# Generated by Django 5.2.15 on 2026-07-06 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('country', models.CharField(help_text="Primary country of the authority, lowercase, e.g. 'ke'", max_length=2, verbose_name='Country (ISO 3166-1 alpha-2)')),
                ('sender_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='Accepted <sender> values. Alerts whose sender does not match are quarantined.', size=None, verbose_name='CAP sender values')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact email')),
                ('active', models.BooleanField(default=True)),
                ('signature_policy', models.CharField(choices=[('require', 'Require valid signature'), ('verify_if_present', 'Verify when present'), ('ignore', 'Ignore signatures')], default='verify_if_present', max_length=20)),
                ('certificate_pem', models.TextField(blank=True, verbose_name='X.509 certificate (PEM)')),
                ('mqtt_username', models.CharField(blank=True, editable=False, max_length=100)),
                ('mqtt_password_hash', models.CharField(blank=True, editable=False, help_text='mosquitto_passwd-compatible hash', max_length=255)),
                ('mqtt_topic', models.CharField(blank=True, editable=False, max_length=255)),
                ('webhook_token', models.CharField(blank=True, editable=False, max_length=64)),
                ('feed_url', models.URLField(help_text='Required. e.g. https://<composer>/api/cap/rss.xml', verbose_name='CAP feed URL (RSS/ATOM)')),
                ('feed_type', models.CharField(choices=[('auto', 'Autodiscover'), ('rss', 'RSS 2.0'), ('atom', 'ATOM')], default='auto', help_text='Leave on Autodiscover to sniff the feed root element', max_length=5)),
                ('feed_type_detected', models.CharField(blank=True, editable=False, help_text="Resolved type when feed_type is 'auto'", max_length=5)),
                ('feed_poll_interval_minutes', models.PositiveIntegerField(default=5, help_text='Used when no push transport is configured or push has gone quiet', verbose_name='Fast poll interval (min)')),
                ('feed_reconcile_interval_minutes', models.PositiveIntegerField(default=30, help_text='Slow sweep used while MQTT/webhook are healthy', verbose_name='Reconcile poll interval (min)')),
                ('feed_etag', models.CharField(blank=True, editable=False, max_length=255)),
                ('feed_last_modified', models.CharField(blank=True, editable=False, max_length=100)),
                ('feed_last_polled', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source Authority',
                'verbose_name_plural': 'Source Authorities',
                'ordering': ['country', 'name'],
            },
        ),
    ]
