# Generated by Django 5.2.15 on 2026-07-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceauthority',
            name='feed_type',
        ),
        migrations.AlterField(
            model_name='sourceauthority',
            name='feed_type_detected',
            field=models.CharField(blank=True, editable=False, help_text='RSS/ATOM, sniffed from the feed during the first successful poll (display only)', max_length=5),
        ),
    ]
