# Generated by Django 5.2.16 on 2026-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_sources', '0003_alter_sourceauthority_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceauthority',
            name='wmo_feed_url',
            field=models.URLField(blank=True, editable=False, verbose_name='WMO registry feed URL (captured)'),
        ),
        migrations.AddField(
            model_name='sourceauthority',
            name='wmo_guid',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='WMO registry GUID'),
        ),
        migrations.AddConstraint(
            model_name='sourceauthority',
            constraint=models.UniqueConstraint(condition=models.Q(('wmo_guid', ''), _negated=True), fields=('wmo_guid',), name='unique_non_empty_wmo_guid'),
        ),
    ]
