# Generated by Django 5.2.16 on 2026-07-08 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_sources', '0003_alter_sourceauthority_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceauthority',
            name='sender_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Accepted <sender> values. Alerts whose sender does not match are quarantined. Leave empty to skip the sender check (attribution still comes from the transport).', size=None, verbose_name='CAP sender values'),
        ),
    ]
