# Generated by Django 5.2.16 on 2026-07-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_sources', '0005_sourceauthority_wmo_feed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceauthority',
            name='website',
            field=models.URLField(blank=True, help_text='Official public website, linked from the frontend Authorities page.', verbose_name='Website'),
        ),
    ]
