# Generated by Django 5.2.16 on 2026-07-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_heading', models.CharField(default='Emergency alerts from official sources, on one map', max_length=255)),
                ('hero_intro', models.TextField(blank=True, default='CAP Aggregator collects Common Alerting Protocol warnings from national meteorological and hydrological services and serves them as one authoritative, always-current picture.')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Optional hero background; a default is used when empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
