# Generated by Django 5.2.15 on 2026-07-06 16:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capagg_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="CAP geocode valueName, e.g. 'EMMA_ID', 'ISO 3166-2'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('authority', models.ForeignKey(blank=True, help_text='Set for national schemes; empty for global ones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geocode_schemes', to='capagg_sources.sourceauthority')),
            ],
        ),
        migrations.CreateModel(
            name='GeocodeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='capagg_geocodes.geocodescheme')),
            ],
            options={
                'indexes': [models.Index(fields=['scheme', 'value'], name='capagg_geoc_scheme__f0a9c3_idx')],
            },
        ),
    ]
