# Generated by Django 5.2.15 on 2026-07-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_geocodes', '0001_initial'),
        ('task_ferry', '0002_add_ingestion_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeImportJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('file_path', models.CharField(max_length=500)),
                ('file_format', models.CharField(choices=[('geojson', 'GeoJSON'), ('csv', 'CSV (WKT column)')], default='geojson', max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Validity window start for imported values', null=True)),
                ('values_created', models.IntegerField(default=0)),
                ('values_updated', models.IntegerField(default=0)),
                ('values_skipped', models.IntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='capagg_geocodes.geocodescheme')),
            ],
            bases=('task_ferry.job',),
        ),
    ]
