"""Generate Mosquitto passwd/ACL files from registered authorities.

Mosquitto's PBKDF2-SHA512 password format ($7$...) is written directly so we
never need the plaintext after issuance.
"""

import base64
import hashlib
import os
from pathlib import Path

from django.conf import settings

PBKDF2_ITERATIONS = 101
SALT_BYTES = 12


def hash_password(password: str) -> str:
    """mosquitto_passwd-compatible hash (format $7$ = PBKDF2-SHA512)."""
    salt = os.urandom(SALT_BYTES)
    derived = hashlib.pbkdf2_hmac("sha512", password.encode(), salt, PBKDF2_ITERATIONS)
    return "$7${}${}${}".format(
        PBKDF2_ITERATIONS,
        base64.b64encode(salt).decode(),
        base64.b64encode(derived).decode(),
    )


def render_auth_files() -> tuple[str, str]:
    """Return (passwd_content, acl_content) for all active authorities + the consumer."""
    from .models import SourceAuthority

    consumer_user = settings.MQTT_CONSUMER_USERNAME
    consumer_hash = hash_password(settings.MQTT_CONSUMER_PASSWORD) if settings.MQTT_CONSUMER_PASSWORD else None

    passwd_lines = []
    acl_lines = [
        "# Generated by `capagg sync_mosquitto` — do not edit by hand.",
        f"user {consumer_user}",
        "topic read cap/in/#",
        "topic write cap/out/#",
        "",
    ]

    if consumer_hash:
        passwd_lines.append(f"{consumer_user}:{consumer_hash}")

    for authority in SourceAuthority.objects.filter(active=True).exclude(mqtt_username=""):
        passwd_lines.append(f"{authority.mqtt_username}:{authority.mqtt_password_hash}")
        acl_lines += [f"user {authority.mqtt_username}", f"topic write {authority.mqtt_topic}", ""]

    return "\n".join(passwd_lines) + "\n", "\n".join(acl_lines) + "\n"


def write_auth_files(directory: str | None = None) -> tuple[Path, Path]:
    """Write passwd/ACL atomically (write-then-rename) so the broker's file
    watcher never sees a half-written file, and hand ownership to the
    mosquitto user inside the broker container (it drops privileges, so a
    root-owned 0600 file would be unreadable)."""
    import os

    directory = Path(directory or settings.MOSQUITTO_AUTH_DIR)
    mosquitto_uid = getattr(settings, "MOSQUITTO_UID", 1883)
    passwd_content, acl_content = render_auth_files()

    paths = []
    for filename, content, mode in (("passwd", passwd_content, 0o600), ("acl", acl_content, 0o644)):
        final = directory / filename
        tmp = directory / f".{filename}.tmp"
        tmp.write_text(content)
        tmp.chmod(mode)
        try:
            os.chown(tmp, mosquitto_uid, mosquitto_uid)
        except (PermissionError, OSError):
            # Not root (e.g. local dev outside docker) — fall back to group/world-readable
            tmp.chmod(0o644)
        tmp.rename(final)
        paths.append(final)

    return paths[0], paths[1]
