# Generated by Django 5.2.15 on 2026-07-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capagg_alerts', '0001_initial'),
        ('capagg_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(choices=[('mqtt', 'MQTT'), ('webhook', 'Webhook'), ('poll', 'Feed poll'), ('manual', 'Manual upload')], max_length=10)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('xml', models.TextField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('stored', 'Stored'), ('quarantined', 'Quarantined'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='CAP <sent> — for latency metrics', null=True)),
                ('error', models.TextField(blank=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_messages', to='capagg_sources.sourceauthority')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantinedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField(default=dict, help_text='Per-check validation results')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('notified', 'Authority notified'), ('resubmitted', 'Resubmitted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('raw_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine', to='capagg_ingestion.rawmessage')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(choices=[('mqtt', 'MQTT'), ('webhook', 'Webhook'), ('poll', 'Feed poll'), ('manual', 'Manual upload')], max_length=10)),
                ('was_first', models.BooleanField(default=False, help_text='This arrival delivered the content')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_receipts', to='capagg_alerts.alert')),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receipts', to='capagg_sources.sourceauthority')),
                ('raw_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receipts', to='capagg_ingestion.rawmessage')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['state', 'received_at'], name='capagg_inge_state_c39253_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['authority', 'received_at'], name='capagg_inge_authori_862090_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryreceipt',
            index=models.Index(fields=['authority', 'transport', 'received_at'], name='capagg_inge_authori_3722bd_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryreceipt',
            index=models.Index(fields=['alert', 'transport'], name='capagg_inge_alert_i_b0e597_idx'),
        ),
    ]
