# Generated by Django 5.2.15 on 2026-07-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_ingestion', '0001_initial'),
        ('capagg_sources', '0002_remove_sourceauthority_feed_type_and_more'),
        ('task_ferry', '0002_add_ingestion_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapBackfillJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('file_path', models.CharField(help_text='Path to the uploaded .xml or .zip file', max_length=500)),
                ('alerts_found', models.IntegerField(default=0)),
                ('alerts_stored', models.IntegerField(default=0)),
                ('alerts_duplicate', models.IntegerField(default=0)),
                ('alerts_quarantined', models.IntegerField(default=0)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_jobs', to='capagg_sources.sourceauthority')),
            ],
            bases=('task_ferry.job',),
        ),
        migrations.CreateModel(
            name='QuarantineRevalidationJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('messages_checked', models.IntegerField(default=0)),
                ('messages_stored', models.IntegerField(default=0)),
                ('messages_still_quarantined', models.IntegerField(default=0)),
                ('authority', models.ForeignKey(blank=True, help_text='Limit to one authority; empty = all', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revalidation_jobs', to='capagg_sources.sourceauthority')),
            ],
            bases=('task_ferry.job',),
        ),
    ]
