# Generated by Django 5.2.15 on 2026-07-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_ingestion', '0002_capbackfilljob_quarantinerevalidationjob'),
        ('capagg_sources', '0002_remove_sourceauthority_feed_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(choices=[('mqtt', 'MQTT'), ('webhook', 'Webhook'), ('poll', 'Feed poll'), ('manual', 'Manual upload')], max_length=10)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('authority', models.ForeignKey(blank=True, help_text='Null for unattributable/global events (bad-token webhook, MQTT consumer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_events', to='capagg_sources.sourceauthority')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['authority', 'occurred_at'], name='capagg_inge_authori_a2d47a_idx')],
            },
        ),
    ]
