# Generated by Django 5.2.16 on 2026-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_ingestion', '0003_sourceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinedmessage',
            name='primary_category',
            field=models.CharField(blank=True, choices=[('schema', 'Schema'), ('identity', 'Identity'), ('signature', 'Signature'), ('reissue', 'Re-issue'), ('lineage', 'Lineage'), ('content', 'Content'), ('internal', 'Internal')], db_index=True, help_text="Most upstream category among this message's findings — denormalized from the report at creation so the list filters with a SQL predicate", max_length=20),
        ),
    ]
