# Generated by Django 5.2.15 on 2026-07-06 16:05

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capagg_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_desc', models.CharField(max_length=512)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('is_circle_derived', models.BooleanField(default=False)),
                ('is_geocode_derived', models.BooleanField(default=False)),
                ('geocodes', models.JSONField(blank=True, default=dict, help_text='scheme → [values]')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('ceiling', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en-US', max_length=20)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('event', models.CharField(max_length=255)),
                ('response_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('urgency', models.CharField(choices=[('Immediate', 'Immediate'), ('Expected', 'Expected'), ('Future', 'Future'), ('Past', 'Past'), ('Unknown', 'Unknown')], max_length=10)),
                ('severity', models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')], max_length=10)),
                ('certainty', models.CharField(choices=[('Observed', 'Observed'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Unlikely', 'Unlikely'), ('Unknown', 'Unknown')], max_length=10)),
                ('audience', models.CharField(blank=True, max_length=255)),
                ('onset', models.DateTimeField(blank=True, null=True)),
                ('effective', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('headline', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('instruction', models.TextField(blank=True)),
                ('web', models.URLField(blank=True, max_length=512)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('event_codes', models.JSONField(blank=True, default=dict)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanglingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_sender', models.CharField(max_length=255)),
                ('ref_identifier', models.CharField(max_length=255)),
                ('ref_sent', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('incomplete_chain', models.BooleanField(default=False, help_text='An Update/Cancel referenced a message we never received')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResolvedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=255)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('urgency', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=10)),
                ('certainty', models.CharField(max_length=10)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('headline', models.CharField(blank=True, max_length=512)),
                ('onset', models.DateTimeField(blank=True, null=True)),
                ('effective', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, size=None)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('geom_z8', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('geom_z5', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('sent', models.DateTimeField()),
                ('msg_type', models.CharField(choices=[('Alert', 'Alert'), ('Update', 'Update'), ('Cancel', 'Cancel'), ('Ack', 'Ack'), ('Error', 'Error')], max_length=10)),
                ('status', models.CharField(choices=[('Actual', 'Actual'), ('Exercise', 'Exercise'), ('System', 'System'), ('Test', 'Test'), ('Draft', 'Draft')], max_length=10)),
                ('scope', models.CharField(max_length=15)),
                ('references', models.JSONField(blank=True, default=list, help_text='Parsed list of {sender, identifier, sent} triples')),
                ('note', models.TextField(blank=True)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='capagg_sources.sourceauthority')),
            ],
            options={
                'ordering': ['-sent'],
            },
        ),
    ]
