# Generated by Django 5.2.15 on 2026-07-06 16:05

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capagg_alerts', '0001_initial'),
        ('capagg_ingestion', '0001_initial'),
        ('capagg_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='raw_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='capagg_ingestion.rawmessage'),
        ),
        migrations.AddField(
            model_name='alertinfo',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='capagg_alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertarea',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='capagg_alerts.alertinfo'),
        ),
        migrations.AddField(
            model_name='danglingreference',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dangling_refs', to='capagg_alerts.alert'),
        ),
        migrations.AddField(
            model_name='eventchain',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chains', to='capagg_sources.sourceauthority'),
        ),
        migrations.AddField(
            model_name='eventchain',
            name='first_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='capagg_alerts.alert'),
        ),
        migrations.AddField(
            model_name='eventchain',
            name='latest_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='capagg_alerts.alert'),
        ),
        migrations.AddField(
            model_name='alert',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='capagg_alerts.eventchain'),
        ),
        migrations.AddField(
            model_name='resolvedalert',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_alerts', to='capagg_sources.sourceauthority'),
        ),
        migrations.AddField(
            model_name='resolvedalert',
            name='chain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolved', to='capagg_alerts.eventchain'),
        ),
        migrations.AddField(
            model_name='resolvedalert',
            name='latest_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='capagg_alerts.alert'),
        ),
        migrations.AddIndex(
            model_name='alertinfo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='capagg_aler_search__8222c5_gin'),
        ),
        migrations.AddIndex(
            model_name='danglingreference',
            index=models.Index(fields=['ref_sender', 'ref_identifier', 'ref_sent', 'resolved'], name='capagg_aler_ref_sen_797597_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['sent'], name='capagg_aler_sent_afa167_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['authority', 'sent'], name='capagg_aler_authori_39b8b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('sender', 'identifier', 'sent'), name='uniq_cap_identity'),
        ),
        migrations.AddIndex(
            model_name='resolvedalert',
            index=models.Index(fields=['effective', 'expires'], name='capagg_aler_effecti_8dced2_idx'),
        ),
        migrations.AddIndex(
            model_name='resolvedalert',
            index=models.Index(fields=['severity'], name='capagg_aler_severit_af63c9_idx'),
        ),
        migrations.AddIndex(
            model_name='resolvedalert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['categories'], name='capagg_aler_categor_63fc4b_gin'),
        ),
        migrations.AddIndex(
            model_name='resolvedalert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['countries'], name='capagg_aler_countri_43d6df_gin'),
        ),
    ]
