# Generated by Django 5.2.16 on 2026-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertarea',
            name='area_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='audience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='web',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resolvedalert',
            name='headline',
            field=models.TextField(blank=True),
        ),
    ]
