# Generated by Django 5.2.16 on 2026-07-21 10:58

from django.db import migrations, models

BATCH = 500


def backfill_fingerprints(apps, schema_editor):
    """Fingerprint alerts already in the table so the re-issue check can compare
    a newly-arrived message against history from its first run, not only against
    alerts ingested after this deploy."""
    from capaggregator.alerts.parser import content_fingerprint

    Alert = apps.get_model("capagg_alerts", "Alert")
    batch = []
    for alert in Alert.objects.select_related("raw_message").iterator(chunk_size=BATCH):
        alert.content_fingerprint = content_fingerprint(alert.raw_message.xml)
        batch.append(alert)
        if len(batch) >= BATCH:
            Alert.objects.bulk_update(batch, ["content_fingerprint"])
            batch = []
    if batch:
        Alert.objects.bulk_update(batch, ["content_fingerprint"])


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_alerts', '0003_alter_alertarea_area_desc_alter_alertinfo_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='content_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='sha256 of the CAP body excluding identifier/sent/effective — see alerts.parser.content_fingerprint. Detects an upstream re-issue of the same alert under a fresh identity triple.', max_length=64),
        ),
        migrations.RunPython(backfill_fingerprints, migrations.RunPython.noop),
    ]
