# Generated by Django 5.2.16 on 2026-07-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_alerts', '0004_alert_content_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='validation_warnings',
        ),
        migrations.AddField(
            model_name='alert',
            name='defect_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Number of AlertDefect rows on this alert — denormalized so admin lists and filters never join the register'),
        ),
        migrations.CreateModel(
            name='AlertDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('schema', 'Schema'), ('identity', 'Identity'), ('signature', 'Signature'), ('reissue', 'Re-issue'), ('lineage', 'Lineage'), ('content', 'Content'), ('internal', 'Internal')], db_index=True, max_length=20)),
                ('check_name', models.CharField(help_text='Name of the check that produced the finding', max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], db_index=True, default='warning', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='capagg_alerts.alert')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'indexes': [models.Index(fields=['category', 'created'], name='capagg_aler_categor_675ecb_idx'), models.Index(fields=['alert', 'category'], name='capagg_aler_alert_i_b359f5_idx')],
            },
        ),
    ]
