# Generated by Django 5.2.16 on 2026-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capagg_alerts', '0005_remove_alert_validation_warnings_alert_defect_count_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertdefect',
            index=models.Index(fields=['created'], name='capagg_aler_created_d88dbc_idx'),
        ),
    ]
